using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Player;

namespace LDH_Test
{
    public class PlayerController : MonoBehaviour
    {
        public PlayerMovement _movement;
        public PlayerStatus _status;
        
        // Update is called once per frame
        void Update()
        {
            MoveTest();
        }
        
        public void MoveTest()
        {
            //(회전 수행 후) 좌우 회전에 대한 벡터 반환
            Vector3 camRotateDir = _movement.SetAimRotation();

            float moveSpeed;
            if (_status.IsAming.Value) moveSpeed = _status.WalkSpeed;
            else moveSpeed = _status.RunSpeed;

            Vector3 moveDir = _movement.SetMove(moveSpeed);
            _status.IsMoving.Value = (moveDir != Vector3.zero);
            
            //몸체의 회전
            

        }


    }

}
